name: Build Python

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.3.1

      - name: Remove wheelhouse directory
        uses: JesseTG/rm@v1.0.2
        with:
          path: wheelhouse

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse ./python
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_REPAIR_WHEEL_COMMAND_MACOS:
          CIBW_REPAIR_WHEEL_COMMAND_LINUX:
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS:

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
