name: Build Python

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Zig
        run: python -m pip install ziglang==0.9.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse ./python
        
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
